### ISSUE TITLE
association with FP and FN

### ISSUE THREAD

**Issue by djmannion** [rogerlew/sdt-metrics#1]
Thanks for this very useful library. I'm confused though about the association of 'miss' and 'false alarm' with 'false positive' and 'false negative' as in this code:

```python
HI,MI,CR,FA = TP,FP,TN,FN
```

I would have thought misses would correspond to false negatives and false alarms to false positives?

**Comment by rogerlew** [comment]
I apparently wasn't watching this repo. Yeah, I think you are right.

With the TP,FP,TN,FN nomenclature, true would be when the even occured, false would be when it didn't occur. Positive would be saying the target is present, negative would be responding that the signal wasn't present.
